name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.12.0
    - name: build rust-regex (rure)
      run: |
          git clone git://github.com/rust-lang/regex
          cd regex/regex-capi
          cargo build --release
    - name: run tests
      run: zig build test
